//! Traversal gym: analytically precise stations built from scaled/rotated
//! `__primitive__/Cube` entities on the gym plateau (rect [80,208]×[−24,104],
//! ground z = 9 — see `params::PLATEAUS`).
//!
//! Every controller threshold gets a PAIR straddling the provisional limit
//! (45° slope / 0.4 m step / 3 m gap) so M6 can verify both sides of each
//! limit. Dimensions are dyadic where possible.
//!
//! Determinism: no `sin`/`cos` calls — ramp rotations use precomputed f32
//! quaternion-component literals.

use game_shared::world_manifest::SpawnPoint;
use rust_engine::engine::scene::scene_format::{ComponentData, EntityData};

use crate::scene::{det_guid, mesh_renderer};

/// Gym plateau ground height (matches the plateau in `params::PLATEAUS`).
const GROUND: f32 = 9.0;
const CUBE: &str = "__primitive__/Cube";
const TINT: [f32; 4] = [0.6, 0.6, 0.65, 1.0];

/// (degrees label, sin(θ/2), cos(θ/2), sin θ) — precomputed so no libm sin
/// enters generated bytes. θ is the ramp inclination.
const RAMP_ANGLES: &[(u32, f32, f32, f32)] = &[
    (30, 0.258_819_04, 0.965_925_83, 0.5),
    (40, 0.342_020_14, 0.939_692_62, 0.642_787_61),
    (44, 0.374_606_59, 0.927_183_85, 0.694_658_37),
    (46, 0.390_731_13, 0.920_504_85, 0.719_339_80),
    (50, 0.422_618_26, 0.906_307_79, 0.766_044_44),
    (60, 0.5, 0.866_025_40, 0.866_025_40),
];
/// 20° landing slope for the sloped-gap station.
const LANDING_20: (u32, f32, f32, f32) = (20, 0.173_648_18, 0.984_807_75, 0.342_020_14);

/// Step risers: 0.2/0.3 walkable, 0.35/0.45 straddle the 0.4 limit, 0.6 over.
const RISERS: &[f32] = &[0.2, 0.3, 0.35, 0.45, 0.6];
/// Gaps between consecutive gauntlet platforms; 2.75/3.25 straddle 3 m.
const GAPS: &[f32] = &[1.0, 2.0, 2.75, 3.25, 4.0];

fn cube(name: String, pos: [f32; 3], rot: [f32; 4], scale: [f32; 3]) -> EntityData {
    EntityData {
        guid: Some(det_guid(&name, 0, 0)),
        components: vec![
            ComponentData::Transform {
                position: pos,
                rotation: rot,
                scale,
            },
            mesh_renderer(CUBE.into(), TINT),
            ComponentData::StaticCollision,
        ],
        name,
    }
}

fn boxy(name: String, pos: [f32; 3], scale: [f32; 3]) -> EntityData {
    cube(name, pos, [0.0, 0.0, 0.0, 1.0], scale)
}

/// Ramp ascending along +X at inclination θ: rotation −θ about world Y.
fn ramp(name: String, foot: [f32; 2], length: f32, width: f32, a: (u32, f32, f32, f32)) -> EntityData {
    let (_, sin_half, cos_half, sin_t) = a;
    cube(
        name,
        [
            foot[0] + length * 0.5, // horizontal shortening ignored: greybox
            foot[1],
            GROUND + length * 0.5 * sin_t,
        ],
        [0.0, -sin_half, 0.0, cos_half],
        [length, width, 1.0],
    )
}

/// Slope array: one ramp per angle, walk-vs-slide pairs around 45°.
fn slopes(out: &mut Vec<EntityData>) {
    for (i, &a) in RAMP_ANGLES.iter().enumerate() {
        out.push(ramp(
            format!("gym_slope_{}", a.0),
            [88.0 + i as f32 * 16.0, 96.0],
            8.0,
            4.0,
            a,
        ));
    }
}

/// Step arrays: for each riser, 5 steps up, a top platform, 5 steps down —
/// one run ascends, the return leg descends.
fn steps(out: &mut Vec<EntityData>) {
    for (i, &r) in RISERS.iter().enumerate() {
        let x0 = 88.0 + i as f32 * 20.0;
        let y = 72.0;
        for k in 0..5 {
            let h = r * (k + 1) as f32;
            out.push(boxy(
                format!("gym_step_{i}_up_{k}"),
                [x0 + k as f32 + 0.5, y, GROUND + h * 0.5],
                [1.0, 4.0, h],
            ));
            out.push(boxy(
                format!("gym_step_{i}_down_{k}"),
                [x0 + 8.5 + (4 - k) as f32, y, GROUND + h * 0.5],
                [1.0, 4.0, h],
            ));
        }
        let top = r * 5.0;
        out.push(boxy(
            format!("gym_step_{i}_top"),
            [x0 + 6.5, y, GROUND + top * 0.5],
            [3.0, 4.0, top],
        ));
    }
}

/// Gap gauntlet: platforms in a row, tops 1 m above ground, gaps between
/// consecutive platforms from `GAPS`. Plus one sloped-landing pair (3 m gap
/// onto a 20° ramp).
fn gaps(out: &mut Vec<EntityData>) {
    let y = 48.0;
    let mut x = 88.0; // west edge of first platform
    for (i, &g) in std::iter::once(&0.0).chain(GAPS.iter()).enumerate() {
        x += g;
        out.push(boxy(
            format!("gym_gap_platform_{i}"),
            [x + 2.0, y, GROUND + 0.5],
            [4.0, 4.0, 1.0],
        ));
        x += 4.0;
    }
    // Sloped landing: jump from a platform across 3 m onto a 20° ramp.
    out.push(boxy(
        "gym_gap_sloped_start".into(),
        [90.0, 40.0, GROUND + 0.5],
        [4.0, 4.0, 1.0],
    ));
    out.push(ramp(
        "gym_gap_sloped_landing".into(),
        [95.0, 40.0],
        8.0,
        4.0,
        LANDING_20,
    ));
}

/// Ramp tower: 3 stories (3 m each), connecting ramps, long-fall drop edge,
/// low-ceiling passage (1.6 m clearance) and a narrow 0.5 m ledge.
fn tower(out: &mut Vec<EntityData>) {
    let (cx, cy) = (96.0, 16.0);
    for s in 0..3 {
        let top = GROUND + 3.0 * (s + 1) as f32;
        out.push(boxy(
            format!("gym_tower_floor_{s}"),
            [cx, cy, top - 0.25],
            [12.0, 12.0, 0.5],
        ));
    }
    // Ramps up: rise 3 m over 8 m → sin θ = 0.375 − sin/cos half-angle
    // literals for θ = asin(0.375) ≈ 22.024°.
    let a = (22, 0.191_012_36, 0.981_586_27, 0.375);
    // Ground → story 0, ascending +X onto the south-west edge.
    out.push(ramp("gym_tower_ramp_0".into(), [84.0, 12.0], 8.0, 3.0, a));
    // Story 0 → 1 and 1 → 2 on alternating sides.
    let mut r1 = ramp("gym_tower_ramp_1".into(), [92.0, 20.0], 8.0, 3.0, a);
    if let ComponentData::Transform { position, .. } = &mut r1.components[0] {
        position[2] += 3.0;
    }
    out.push(r1);
    let mut r2 = ramp("gym_tower_ramp_2".into(), [92.0, 12.0], 8.0, 3.0, a);
    if let ComponentData::Transform { position, .. } = &mut r2.components[0] {
        position[2] += 6.0;
    }
    out.push(r2);
    // Low-ceiling passage on story 0: slab 1.6 m above the floor.
    out.push(boxy(
        "gym_tower_low_ceiling".into(),
        [96.0, 20.0, GROUND + 3.0 + 1.6 + 0.25],
        [6.0, 4.0, 0.5],
    ));
    // Narrow ledge off the top story (east edge), 0.5 m wide.
    out.push(boxy(
        "gym_tower_ledge".into(),
        [106.0, 16.0, GROUND + 9.0 - 0.25],
        [8.0, 0.5, 0.5],
    ));
    // Drop-edge landing pad at the tower's north side (long fall reference).
    out.push(boxy(
        "gym_tower_drop_pad".into(),
        [96.0, 26.0, GROUND + 0.125],
        [6.0, 6.0, 0.25],
    ));
}

/// Corner block: inside corner, outside corner, and a 16 m slide-along wall.
fn corners(out: &mut Vec<EntityData>) {
    let z = GROUND + 1.5;
    // Inside corner (L opening to the north-east).
    out.push(boxy("gym_corner_in_a".into(), [140.0, 12.0, z], [8.0, 0.5, 3.0]));
    out.push(boxy("gym_corner_in_b".into(), [136.25, 16.0, z], [0.5, 8.5, 3.0]));
    // Outside corner block to walk around.
    out.push(boxy("gym_corner_out".into(), [156.0, 16.0, z], [4.0, 4.0, 3.0]));
    // Long wall for slide-along.
    out.push(boxy("gym_corner_wall".into(), [172.0, 12.0, z], [16.0, 0.5, 3.0]));
}

/// Seam routes: a walled corridor with a threshold step crossing the cell
/// border x = 128, and another crossing the zone border y = 0 — collision,
/// streaming and replication all cross seams on the same geometry.
fn seams(out: &mut Vec<EntityData>) {
    // Cell-border corridor along X, centered on x = 128.
    out.push(boxy("gym_seam_cell_wall_s".into(), [128.0, 30.0, GROUND + 1.5], [16.0, 0.5, 3.0]));
    out.push(boxy("gym_seam_cell_wall_n".into(), [128.0, 34.0, GROUND + 1.5], [16.0, 0.5, 3.0]));
    // Threshold step exactly straddling the border (0.35 riser).
    out.push(boxy("gym_seam_cell_step".into(), [128.0, 32.0, GROUND + 0.175], [2.0, 3.5, 0.35]));
    // Zone-border corridor along Y, centered on y = 0.
    out.push(boxy("gym_seam_zone_wall_w".into(), [98.0, 0.0, GROUND + 1.5], [0.5, 16.0, 3.0]));
    out.push(boxy("gym_seam_zone_wall_e".into(), [102.0, 0.0, GROUND + 1.5], [0.5, 16.0, 3.0]));
    out.push(boxy("gym_seam_zone_step".into(), [100.0, 0.0, GROUND + 0.175], [3.5, 2.0, 0.35]));
}

/// All gym entities (deterministic order — scene bytes depend on it).
pub fn gym_entities() -> Vec<EntityData> {
    let mut out = Vec::new();
    slopes(&mut out);
    steps(&mut out);
    gaps(&mut out);
    tower(&mut out);
    corners(&mut out);
    seams(&mut out);
    out
}

/// One named spawn point per station (M6 teleports between them).
pub fn gym_spawn_points() -> Vec<SpawnPoint> {
    let p = |name: &str, x: f32, y: f32, z: f32| SpawnPoint {
        name: name.into(),
        position: [x, y, z],
    };
    vec![
        p("gym_slopes", 84.0, 96.0, GROUND),
        p("gym_steps", 84.0, 72.0, GROUND),
        p("gym_gaps", 90.0, 48.0, GROUND + 1.0),
        p("gym_gap_sloped", 90.0, 40.0, GROUND + 1.0),
        p("gym_tower", 84.0, 8.0, GROUND),
        p("gym_corners", 144.0, 20.0, GROUND),
        p("gym_seam_cell", 121.0, 32.0, GROUND),
        p("gym_seam_zone", 100.0, -6.0, GROUND),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::params::PLATEAUS;

    #[test]
    fn names_and_guids_are_unique() {
        let ents = gym_entities();
        let mut names: Vec<_> = ents.iter().map(|e| e.name.clone()).collect();
        names.sort();
        names.dedup();
        assert_eq!(names.len(), ents.len());
        let mut guids: Vec<_> = ents.iter().map(|e| e.guid.clone().unwrap()).collect();
        guids.sort();
        guids.dedup();
        assert_eq!(guids.len(), ents.len());
    }

    #[test]
    fn all_stations_sit_on_the_gym_plateau_or_seam_corridors() {
        // Gym plateau rect plus its southern seam corridor extension.
        let gym = &PLATEAUS[1];
        for e in gym_entities() {
            let ComponentData::Transform { position, .. } = e.components[0] else {
                panic!("first component must be Transform");
            };
            assert!(
                position[0] >= gym.min[0] && position[0] <= gym.max[0],
                "{} x={}",
                e.name,
                position[0]
            );
            assert!(
                position[1] >= gym.min[1] && position[1] <= gym.max[1],
                "{} y={}",
                e.name,
                position[1]
            );
        }
    }

    #[test]
    fn seam_stations_straddle_the_borders() {
        let ents = gym_entities();
        let find = |n: &str| {
            let e = ents.iter().find(|e| e.name == n).unwrap();
            let ComponentData::Transform { position, scale, .. } = e.components[0] else {
                unreachable!()
            };
            (position, scale)
        };
        let (p, s) = find("gym_seam_cell_step");
        assert!(p[0] - s[0] * 0.5 < 128.0 && p[0] + s[0] * 0.5 > 128.0);
        let (p, s) = find("gym_seam_zone_step");
        assert!(p[1] - s[1] * 0.5 < 0.0 && p[1] + s[1] * 0.5 > 0.0);
    }
}
