//! Derive macros for the Task 40 node graph framework.
//!
//! `#[derive(ScriptNode)]` (generic) and `#[derive(AnimationNode)]` (first
//! domain macro, proving the layering for Task 41) both lower a plain struct
//! into an inherent `fn descriptor() -> NodeDescriptor`, matching the runtime
//! types in `rust_engine::engine::node_graph` exactly. The two derives are
//! thin wrappers over one shared parse/generate core (`expand`).
//!
//! Grammar (see `docs/roadmap/VULKANO-40-NODE-GRAPH-FRAMEWORK.md` D9):
//! ```ignore
//! #[derive(ScriptNode)]
//! #[node(id = "damage_zone", name = "Damage Zone", category = "Gameplay",
//!        pure = false, realm = "shared", deterministic = true,
//!        version = 1, auto_register)]
//! pub struct DamageZone {
//!     #[input(pin = "exec", doc = "Runs when this fires")] exec_in: ExecPin,
//!     #[input(label = "DPS", default = 10.0)] dps: f32,
//!     #[input(label = "Radius")] radius: f32,
//!     #[output(pin = "exec")] exec_out: ExecPin,
//!     #[output(label = "Entities Hit")] hit_count: f32,
//! }
//! ```

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{spanned::Spanned, Data, DeriveInput, Fields, Lit, Type};

/// Path prefix for the engine's node graph types. `extern crate self as
/// rust_engine;` in the engine crate makes this resolve when the derive is
/// applied to types defined inside the engine itself.
fn ng() -> TokenStream2 {
    quote! { ::rust_engine::engine::node_graph }
}

#[proc_macro_derive(ScriptNode, attributes(node, input, output))]
pub fn derive_script_node(input: TokenStream) -> TokenStream {
    expand(input)
}

#[proc_macro_derive(AnimationNode, attributes(node, input, output))]
pub fn derive_animation_node(input: TokenStream) -> TokenStream {
    expand(input)
}

/// Shared parse/generate core for every node derive.
fn expand(input: TokenStream) -> TokenStream {
    let ast = syn::parse_macro_input!(input as DeriveInput);
    match build(&ast) {
        Ok(ts) => ts.into(),
        Err(e) => e.to_compile_error().into(),
    }
}

struct NodeMeta {
    id: String,
    name: String,
    category: String,
    pure: bool,
    realm: String,
    deterministic: bool,
    version: u32,
    auto_register: bool,
    doc: Option<String>,
}

fn build(ast: &DeriveInput) -> syn::Result<TokenStream2> {
    let ident = &ast.ident;
    let meta = parse_node_attr(ast)?;

    let fields = match &ast.data {
        Data::Struct(s) => match &s.fields {
            Fields::Named(named) => &named.named,
            _ => {
                return Err(syn::Error::new(
                    ast.span(),
                    "node derives require a struct with named fields",
                ))
            }
        },
        _ => {
            return Err(syn::Error::new(
                ast.span(),
                "node derives may only be applied to structs",
            ))
        }
    };

    let mut inputs = Vec::new();
    let mut outputs = Vec::new();
    for field in fields {
        let (side, pin) = parse_field(field)?;
        match side {
            Side::Input => inputs.push(pin),
            Side::Output => outputs.push(pin),
            Side::None => {} // no #[input]/#[output]: not a pin, skip
        }
    }

    let ng = ng();
    let realm = realm_tokens(&meta.realm, ast.span())?;
    let (id, name, category, pure, deterministic, version) = (
        &meta.id,
        &meta.name,
        &meta.category,
        meta.pure,
        meta.deterministic,
        meta.version,
    );
    let doc = match &meta.doc {
        Some(d) => quote! { ::std::option::Option::Some(#d.to_string()) },
        None => quote! { ::std::option::Option::None },
    };

    let descriptor = quote! {
        impl #ident {
            /// Node type descriptor generated by the node graph derive macro.
            pub fn descriptor() -> #ng::registry::NodeDescriptor {
                use #ng::registry::{NodeDescriptor, PinDescriptor};
                use #ng::doc::{PinType, PropValue, NodeRealm};
                NodeDescriptor {
                    id: #id.to_string(),
                    name: #name.to_string(),
                    category: #category.to_string(),
                    version: #version,
                    inputs: ::std::vec![ #(#inputs),* ],
                    outputs: ::std::vec![ #(#outputs),* ],
                    pure: #pure,
                    realm: #realm,
                    deterministic: #deterministic,
                    doc: #doc,
                }
            }
        }
    };

    let auto = if meta.auto_register {
        quote! {
            ::inventory::submit! {
                #ng::auto_register::NodeFactory(<#ident>::descriptor)
            }
        }
    } else {
        quote! {}
    };

    Ok(quote! {
        #descriptor
        #auto
    })
}

fn parse_node_attr(ast: &DeriveInput) -> syn::Result<NodeMeta> {
    let attr = ast
        .attrs
        .iter()
        .find(|a| a.path().is_ident("node"))
        .ok_or_else(|| {
            syn::Error::new(ast.span(), "missing #[node(...)] attribute on node struct")
        })?;

    let mut id = None;
    let mut name = None;
    let mut category = None;
    let mut pure = None;
    let mut realm = None;
    let mut deterministic = None;
    let mut version: u32 = 1;
    let mut auto_register = false;
    let mut doc: Option<String> = None;

    attr.parse_nested_meta(|meta| {
        let key = meta
            .path
            .get_ident()
            .map(|i| i.to_string())
            .unwrap_or_default();
        match key.as_str() {
            "auto_register" => {
                auto_register = true;
                Ok(())
            }
            "id" => {
                id = Some(lit_string(&meta)?);
                Ok(())
            }
            "name" => {
                name = Some(lit_string(&meta)?);
                Ok(())
            }
            "category" => {
                category = Some(lit_string(&meta)?);
                Ok(())
            }
            "realm" => {
                realm = Some(lit_string(&meta)?);
                Ok(())
            }
            "pure" => {
                pure = Some(lit_bool(&meta)?);
                Ok(())
            }
            "deterministic" => {
                deterministic = Some(lit_bool(&meta)?);
                Ok(())
            }
            "version" => {
                let value = meta.value()?;
                let lit: syn::LitInt = value.parse()?;
                version = lit.base10_parse()?;
                Ok(())
            }
            "doc" => {
                doc = Some(lit_string(&meta)?);
                Ok(())
            }
            other => Err(meta.error(format!("unknown #[node] key `{other}`"))),
        }
    })?;

    let missing = |field: &str| syn::Error::new(attr.span(), format!("#[node] missing `{field}`"));
    Ok(NodeMeta {
        id: id.ok_or_else(|| missing("id"))?,
        name: name.ok_or_else(|| missing("name"))?,
        category: category.ok_or_else(|| missing("category"))?,
        pure: pure.ok_or_else(|| missing("pure"))?,
        realm: realm.ok_or_else(|| missing("realm"))?,
        deterministic: deterministic.ok_or_else(|| missing("deterministic"))?,
        version,
        auto_register,
        doc,
    })
}

fn lit_string(meta: &syn::meta::ParseNestedMeta) -> syn::Result<String> {
    let value = meta.value()?;
    let lit: syn::LitStr = value.parse()?;
    Ok(lit.value())
}

fn lit_bool(meta: &syn::meta::ParseNestedMeta) -> syn::Result<bool> {
    let value = meta.value()?;
    let lit: syn::LitBool = value.parse()?;
    Ok(lit.value())
}

enum Side {
    Input,
    Output,
    None,
}

fn parse_field(field: &syn::Field) -> syn::Result<(Side, TokenStream2)> {
    let field_ident = field.ident.as_ref().expect("named field");
    let slug = field_ident.to_string();

    let (side, attr) = if let Some(a) = field.attrs.iter().find(|a| a.path().is_ident("input")) {
        (Side::Input, Some(a))
    } else if let Some(a) = field.attrs.iter().find(|a| a.path().is_ident("output")) {
        (Side::Output, Some(a))
    } else {
        (Side::None, None)
    };

    let attr = match attr {
        Some(a) => a,
        None => return Ok((Side::None, quote! {})),
    };

    // Field-level options.
    let mut label: Option<String> = None;
    let mut pin_kind: Option<String> = None;
    let mut default_lit: Option<Lit> = None;
    let mut doc: Option<String> = None;

    // An attribute with no args (e.g. `#[output]`) has no meta list to parse.
    if !matches!(attr.meta, syn::Meta::Path(_)) {
        attr.parse_nested_meta(|meta| {
            let key = meta
                .path
                .get_ident()
                .map(|i| i.to_string())
                .unwrap_or_default();
            match key.as_str() {
                "label" => {
                    label = Some(lit_string(&meta)?);
                    Ok(())
                }
                "pin" => {
                    pin_kind = Some(lit_string(&meta)?);
                    Ok(())
                }
                "default" => {
                    let value = meta.value()?;
                    default_lit = Some(value.parse()?);
                    Ok(())
                }
                "doc" => {
                    doc = Some(lit_string(&meta)?);
                    Ok(())
                }
                other => Err(meta.error(format!("unknown #[input]/#[output] key `{other}`"))),
            }
        })?;
    }

    let label = label.unwrap_or_else(|| title_case(&slug));
    let pin_ty = pin_type_tokens(&field.ty, pin_kind.as_deref(), field.span())?;

    let default_tokens = match default_lit {
        Some(lit) => {
            let pv = prop_value_tokens(&lit)?;
            quote! { .with_default(#pv) }
        }
        None => quote! {},
    };

    let doc_tokens = match doc {
        Some(d) => quote! { .with_doc(#d) },
        None => quote! {},
    };

    let pin = quote! {
        PinDescriptor::new(#slug, #label, #pin_ty) #default_tokens #doc_tokens
    };
    Ok((side, pin))
}

/// Map a field's Rust type (and optional explicit `pin = "..."` kind) to a
/// `PinType` expression. `pin = "exec"` forces an exec pin regardless of the
/// field's marker type.
fn pin_type_tokens(
    ty: &Type,
    pin_kind: Option<&str>,
    span: proc_macro2::Span,
) -> syn::Result<TokenStream2> {
    if let Some(kind) = pin_kind {
        if kind == "exec" {
            return Ok(quote! { PinType::Exec });
        }
    }

    match ty {
        Type::Path(p) => {
            let ident = p
                .path
                .segments
                .last()
                .map(|s| s.ident.to_string())
                .unwrap_or_default();
            let variant = match ident.as_str() {
                "ExecPin" => quote! { PinType::Exec },
                "f32" => quote! { PinType::Float },
                "bool" => quote! { PinType::Bool },
                "Vec2" => quote! { PinType::Vec2 },
                "Vec3" => quote! { PinType::Vec3 },
                "Vec4" => quote! { PinType::Vec4 },
                other => {
                    return Err(syn::Error::new(
                        span,
                        format!(
                            "unsupported node pin type `{other}` (supported: f32, bool, \
                             [f32; 2..4], Vec2/Vec3/Vec4, ExecPin)"
                        ),
                    ))
                }
            };
            Ok(variant)
        }
        Type::Array(arr) => {
            let elem_ok = matches!(&*arr.elem, Type::Path(p) if p.path.is_ident("f32"));
            if !elem_ok {
                return Err(syn::Error::new(
                    span,
                    "unsupported node pin array type (only [f32; 2..4] is supported)",
                ));
            }
            let len = match &arr.len {
                syn::Expr::Lit(syn::ExprLit {
                    lit: Lit::Int(n), ..
                }) => n.base10_parse::<usize>()?,
                _ => {
                    return Err(syn::Error::new(
                        span,
                        "node pin array length must be a literal (2, 3 or 4)",
                    ))
                }
            };
            match len {
                2 => Ok(quote! { PinType::Vec2 }),
                3 => Ok(quote! { PinType::Vec3 }),
                4 => Ok(quote! { PinType::Vec4 }),
                _ => Err(syn::Error::new(
                    span,
                    "node pin array length must be 2, 3 or 4",
                )),
            }
        }
        _ => Err(syn::Error::new(
            span,
            "unsupported node pin type (supported: f32, bool, [f32; 2..4], \
             Vec2/Vec3/Vec4, ExecPin)",
        )),
    }
}

/// Map a `default = <lit>` literal to the matching `PropValue` expression.
fn prop_value_tokens(lit: &Lit) -> syn::Result<TokenStream2> {
    match lit {
        Lit::Float(f) => Ok(quote! { PropValue::Float(#f as f32) }),
        Lit::Int(i) => Ok(quote! { PropValue::Float(#i as f32) }),
        Lit::Bool(b) => Ok(quote! { PropValue::Bool(#b) }),
        Lit::Str(s) => Ok(quote! { PropValue::Enum(#s.to_string()) }),
        other => Err(syn::Error::new(
            other.span(),
            "unsupported `default` literal (supported: float, int, bool, string)",
        )),
    }
}

/// `hit_count` -> `Hit Count`, `dps` -> `Dps`.
fn title_case(slug: &str) -> String {
    slug.split('_')
        .filter(|w| !w.is_empty())
        .map(|w| {
            let mut chars = w.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn realm_tokens(realm: &str, span: proc_macro2::Span) -> syn::Result<TokenStream2> {
    match realm {
        "editor" => Ok(quote! { NodeRealm::Editor }),
        "client" => Ok(quote! { NodeRealm::Client }),
        "shared" => Ok(quote! { NodeRealm::Shared }),
        "server_safe" => Ok(quote! { NodeRealm::ServerSafe }),
        other => Err(syn::Error::new(
            span,
            format!(
                "unknown realm `{other}` (expected editor, client, shared or server_safe)"
            ),
        )),
    }
}
