// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AbilityCooldown {
    pub key: u64,
    pub entity_id: u64,
    pub ability_id: u16,
    pub ready_at_micros: i64,
}

impl __sdk::InModule for AbilityCooldown {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AbilityCooldown`.
///
/// Provides typed access to columns for query building.
pub struct AbilityCooldownCols {
    pub key: __sdk::__query_builder::Col<AbilityCooldown, u64>,
    pub entity_id: __sdk::__query_builder::Col<AbilityCooldown, u64>,
    pub ability_id: __sdk::__query_builder::Col<AbilityCooldown, u16>,
    pub ready_at_micros: __sdk::__query_builder::Col<AbilityCooldown, i64>,
}

impl __sdk::__query_builder::HasCols for AbilityCooldown {
    type Cols = AbilityCooldownCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AbilityCooldownCols {
            key: __sdk::__query_builder::Col::new(table_name, "key"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            ability_id: __sdk::__query_builder::Col::new(table_name, "ability_id"),
            ready_at_micros: __sdk::__query_builder::Col::new(table_name, "ready_at_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `AbilityCooldown`.
///
/// Provides typed access to indexed columns for query building.
pub struct AbilityCooldownIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<AbilityCooldown, u64>,
    pub key: __sdk::__query_builder::IxCol<AbilityCooldown, u64>,
}

impl __sdk::__query_builder::HasIxCols for AbilityCooldown {
    type IxCols = AbilityCooldownIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AbilityCooldownIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            key: __sdk::__query_builder::IxCol::new(table_name, "key"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AbilityCooldown {}
