// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::ability_cooldown_type::AbilityCooldown;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `ability_cooldown`.
///
/// Obtain a handle from the [`AbilityCooldownTableAccess::ability_cooldown`] method on [`super::RemoteTables`],
/// like `ctx.db.ability_cooldown()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ability_cooldown().on_insert(...)`.
pub struct AbilityCooldownTableHandle<'ctx> {
    imp: __sdk::TableHandle<AbilityCooldown>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `ability_cooldown`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AbilityCooldownTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AbilityCooldownTableHandle`], which mediates access to the table `ability_cooldown`.
    fn ability_cooldown(&self) -> AbilityCooldownTableHandle<'_>;
}

impl AbilityCooldownTableAccess for super::RemoteTables {
    fn ability_cooldown(&self) -> AbilityCooldownTableHandle<'_> {
        AbilityCooldownTableHandle {
            imp: self.imp.get_table::<AbilityCooldown>("ability_cooldown"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AbilityCooldownInsertCallbackId(__sdk::CallbackId);
pub struct AbilityCooldownDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AbilityCooldownTableHandle<'ctx> {
    type Row = AbilityCooldown;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AbilityCooldown> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AbilityCooldownInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AbilityCooldownInsertCallbackId {
        AbilityCooldownInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AbilityCooldownInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AbilityCooldownDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AbilityCooldownDeleteCallbackId {
        AbilityCooldownDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AbilityCooldownDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AbilityCooldownUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AbilityCooldownTableHandle<'ctx> {
    type UpdateCallbackId = AbilityCooldownUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AbilityCooldownUpdateCallbackId {
        AbilityCooldownUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AbilityCooldownUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `key` unique index on the table `ability_cooldown`,
/// which allows point queries on the field of the same name
/// via the [`AbilityCooldownKeyUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.ability_cooldown().key().find(...)`.
pub struct AbilityCooldownKeyUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AbilityCooldown, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AbilityCooldownTableHandle<'ctx> {
    /// Get a handle on the `key` unique index on the table `ability_cooldown`.
    pub fn key(&self) -> AbilityCooldownKeyUnique<'ctx> {
        AbilityCooldownKeyUnique {
            imp: self.imp.get_unique_constraint::<u64>("key"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AbilityCooldownKeyUnique<'ctx> {
    /// Find the subscribed row whose `key` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AbilityCooldown> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AbilityCooldown>("ability_cooldown");
    _table.add_unique_constraint::<u64>("key", |row| &row.key);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AbilityCooldown>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AbilityCooldown>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AbilityCooldown`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait ability_cooldownQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AbilityCooldown`.
    fn ability_cooldown(&self) -> __sdk::__query_builder::Table<AbilityCooldown>;
}

impl ability_cooldownQueryTableAccess for __sdk::QueryTableAccessor {
    fn ability_cooldown(&self) -> __sdk::__query_builder::Table<AbilityCooldown> {
        __sdk::__query_builder::Table::new("ability_cooldown")
    }
}
