// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Account {
    pub identity: __sdk::Identity,
    pub character_id: u64,
    pub name: String,
    pub created_at_micros: i64,
}

impl __sdk::InModule for Account {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Account`.
///
/// Provides typed access to columns for query building.
pub struct AccountCols {
    pub identity: __sdk::__query_builder::Col<Account, __sdk::Identity>,
    pub character_id: __sdk::__query_builder::Col<Account, u64>,
    pub name: __sdk::__query_builder::Col<Account, String>,
    pub created_at_micros: __sdk::__query_builder::Col<Account, i64>,
}

impl __sdk::__query_builder::HasCols for Account {
    type Cols = AccountCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            created_at_micros: __sdk::__query_builder::Col::new(table_name, "created_at_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `Account`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountIxCols {
    pub character_id: __sdk::__query_builder::IxCol<Account, u64>,
    pub identity: __sdk::__query_builder::IxCol<Account, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for Account {
    type IxCols = AccountIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Account {}
