// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::active_cast_type::ActiveCast;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `active_cast`.
///
/// Obtain a handle from the [`ActiveCastTableAccess::active_cast`] method on [`super::RemoteTables`],
/// like `ctx.db.active_cast()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_cast().on_insert(...)`.
pub struct ActiveCastTableHandle<'ctx> {
    imp: __sdk::TableHandle<ActiveCast>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `active_cast`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActiveCastTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ActiveCastTableHandle`], which mediates access to the table `active_cast`.
    fn active_cast(&self) -> ActiveCastTableHandle<'_>;
}

impl ActiveCastTableAccess for super::RemoteTables {
    fn active_cast(&self) -> ActiveCastTableHandle<'_> {
        ActiveCastTableHandle {
            imp: self.imp.get_table::<ActiveCast>("active_cast"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ActiveCastInsertCallbackId(__sdk::CallbackId);
pub struct ActiveCastDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ActiveCastTableHandle<'ctx> {
    type Row = ActiveCast;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ActiveCast> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ActiveCastInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveCastInsertCallbackId {
        ActiveCastInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActiveCastInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ActiveCastDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveCastDeleteCallbackId {
        ActiveCastDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActiveCastDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ActiveCastUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ActiveCastTableHandle<'ctx> {
    type UpdateCallbackId = ActiveCastUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ActiveCastUpdateCallbackId {
        ActiveCastUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ActiveCastUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `active_cast`,
/// which allows point queries on the field of the same name
/// via the [`ActiveCastEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_cast().entity_id().find(...)`.
pub struct ActiveCastEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ActiveCast, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ActiveCastTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `active_cast`.
    pub fn entity_id(&self) -> ActiveCastEntityIdUnique<'ctx> {
        ActiveCastEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ActiveCastEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ActiveCast> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ActiveCast>("active_cast");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ActiveCast>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ActiveCast>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ActiveCast`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait active_castQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ActiveCast`.
    fn active_cast(&self) -> __sdk::__query_builder::Table<ActiveCast>;
}

impl active_castQueryTableAccess for __sdk::QueryTableAccessor {
    fn active_cast(&self) -> __sdk::__query_builder::Table<ActiveCast> {
        __sdk::__query_builder::Table::new("active_cast")
    }
}
