// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ActiveCast {
    pub entity_id: u64,
    pub ability_id: u16,
    pub target_entity_id: u64,
    pub cell_id: u64,
    pub start_micros: i64,
    pub finish_micros: i64,
}

impl __sdk::InModule for ActiveCast {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ActiveCast`.
///
/// Provides typed access to columns for query building.
pub struct ActiveCastCols {
    pub entity_id: __sdk::__query_builder::Col<ActiveCast, u64>,
    pub ability_id: __sdk::__query_builder::Col<ActiveCast, u16>,
    pub target_entity_id: __sdk::__query_builder::Col<ActiveCast, u64>,
    pub cell_id: __sdk::__query_builder::Col<ActiveCast, u64>,
    pub start_micros: __sdk::__query_builder::Col<ActiveCast, i64>,
    pub finish_micros: __sdk::__query_builder::Col<ActiveCast, i64>,
}

impl __sdk::__query_builder::HasCols for ActiveCast {
    type Cols = ActiveCastCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ActiveCastCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            ability_id: __sdk::__query_builder::Col::new(table_name, "ability_id"),
            target_entity_id: __sdk::__query_builder::Col::new(table_name, "target_entity_id"),
            cell_id: __sdk::__query_builder::Col::new(table_name, "cell_id"),
            start_micros: __sdk::__query_builder::Col::new(table_name, "start_micros"),
            finish_micros: __sdk::__query_builder::Col::new(table_name, "finish_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `ActiveCast`.
///
/// Provides typed access to indexed columns for query building.
pub struct ActiveCastIxCols {
    pub cell_id: __sdk::__query_builder::IxCol<ActiveCast, u64>,
    pub entity_id: __sdk::__query_builder::IxCol<ActiveCast, u64>,
}

impl __sdk::__query_builder::HasIxCols for ActiveCast {
    type IxCols = ActiveCastIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ActiveCastIxCols {
            cell_id: __sdk::__query_builder::IxCol::new(table_name, "cell_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ActiveCast {}
