// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CastAbilityArgs {
    pub ability_id: u16,
    pub target_entity_id: u64,
}

impl From<CastAbilityArgs> for super::Reducer {
    fn from(args: CastAbilityArgs) -> Self {
        Self::CastAbility {
            ability_id: args.ability_id,
            target_entity_id: args.target_entity_id,
        }
    }
}

impl __sdk::InModule for CastAbilityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cast_ability`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cast_ability {
    /// Request that the remote module invoke the reducer `cast_ability` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cast_ability:cast_ability_then`] to run a callback after the reducer completes.
    fn cast_ability(&self, ability_id: u16, target_entity_id: u64) -> __sdk::Result<()> {
        self.cast_ability_then(ability_id, target_entity_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cast_ability` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cast_ability_then(
        &self,
        ability_id: u16,
        target_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cast_ability for super::RemoteReducers {
    fn cast_ability_then(
        &self,
        ability_id: u16,
        target_entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CastAbilityArgs {
                ability_id,
                target_entity_id,
            },
            callback,
        )
    }
}
