// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::clock_type::Clock;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `clock`.
///
/// Obtain a handle from the [`ClockTableAccess::clock`] method on [`super::RemoteTables`],
/// like `ctx.db.clock()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.clock().on_insert(...)`.
pub struct ClockTableHandle<'ctx> {
    imp: __sdk::TableHandle<Clock>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `clock`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClockTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClockTableHandle`], which mediates access to the table `clock`.
    fn clock(&self) -> ClockTableHandle<'_>;
}

impl ClockTableAccess for super::RemoteTables {
    fn clock(&self) -> ClockTableHandle<'_> {
        ClockTableHandle {
            imp: self.imp.get_table::<Clock>("clock"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClockInsertCallbackId(__sdk::CallbackId);
pub struct ClockDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ClockTableHandle<'ctx> {
    type Row = Clock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Clock> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClockInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClockInsertCallbackId {
        ClockInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClockInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClockDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClockDeleteCallbackId {
        ClockDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClockDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ClockUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClockTableHandle<'ctx> {
    type UpdateCallbackId = ClockUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClockUpdateCallbackId {
        ClockUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClockUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `clock`,
/// which allows point queries on the field of the same name
/// via the [`ClockIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.clock().id().find(...)`.
pub struct ClockIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Clock, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClockTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `clock`.
    pub fn id(&self) -> ClockIdUnique<'ctx> {
        ClockIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClockIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Clock> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Clock>("clock");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Clock>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Clock>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Clock`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait clockQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Clock`.
    fn clock(&self) -> __sdk::__query_builder::Table<Clock>;
}

impl clockQueryTableAccess for __sdk::QueryTableAccessor {
    fn clock(&self) -> __sdk::__query_builder::Table<Clock> {
        __sdk::__query_builder::Table::new("clock")
    }
}
