// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Clock {
    pub id: u32,
    pub tick: u64,
    pub server_time_micros: i64,
}

impl __sdk::InModule for Clock {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Clock`.
///
/// Provides typed access to columns for query building.
pub struct ClockCols {
    pub id: __sdk::__query_builder::Col<Clock, u32>,
    pub tick: __sdk::__query_builder::Col<Clock, u64>,
    pub server_time_micros: __sdk::__query_builder::Col<Clock, i64>,
}

impl __sdk::__query_builder::HasCols for Clock {
    type Cols = ClockCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ClockCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            tick: __sdk::__query_builder::Col::new(table_name, "tick"),
            server_time_micros: __sdk::__query_builder::Col::new(table_name, "server_time_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `Clock`.
///
/// Provides typed access to indexed columns for query building.
pub struct ClockIxCols {
    pub id: __sdk::__query_builder::IxCol<Clock, u32>,
}

impl __sdk::__query_builder::HasIxCols for Clock {
    type IxCols = ClockIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ClockIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Clock {}
