// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Config {
    pub id: u32,
    pub protocol_version: u32,
    pub realm_id: u32,
    pub collision_manifest_hash: u64,
}

impl __sdk::InModule for Config {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Config`.
///
/// Provides typed access to columns for query building.
pub struct ConfigCols {
    pub id: __sdk::__query_builder::Col<Config, u32>,
    pub protocol_version: __sdk::__query_builder::Col<Config, u32>,
    pub realm_id: __sdk::__query_builder::Col<Config, u32>,
    pub collision_manifest_hash: __sdk::__query_builder::Col<Config, u64>,
}

impl __sdk::__query_builder::HasCols for Config {
    type Cols = ConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ConfigCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            protocol_version: __sdk::__query_builder::Col::new(table_name, "protocol_version"),
            realm_id: __sdk::__query_builder::Col::new(table_name, "realm_id"),
            collision_manifest_hash: __sdk::__query_builder::Col::new(
                table_name,
                "collision_manifest_hash",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `Config`.
///
/// Provides typed access to indexed columns for query building.
pub struct ConfigIxCols {
    pub id: __sdk::__query_builder::IxCol<Config, u32>,
}

impl __sdk::__query_builder::HasIxCols for Config {
    type IxCols = ConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ConfigIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Config {}
