// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DespawnNpcArgs {
    pub entity_id: u64,
}

impl From<DespawnNpcArgs> for super::Reducer {
    fn from(args: DespawnNpcArgs) -> Self {
        Self::DespawnNpc {
            entity_id: args.entity_id,
        }
    }
}

impl __sdk::InModule for DespawnNpcArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `despawn_npc`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait despawn_npc {
    /// Request that the remote module invoke the reducer `despawn_npc` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`despawn_npc:despawn_npc_then`] to run a callback after the reducer completes.
    fn despawn_npc(&self, entity_id: u64) -> __sdk::Result<()> {
        self.despawn_npc_then(entity_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `despawn_npc` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn despawn_npc_then(
        &self,
        entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl despawn_npc for super::RemoteReducers {
    fn despawn_npc_then(
        &self,
        entity_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DespawnNpcArgs { entity_id }, callback)
    }
}
