// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DevDamageArgs {
    pub entity_id: u64,
    pub amount: f32,
}

impl From<DevDamageArgs> for super::Reducer {
    fn from(args: DevDamageArgs) -> Self {
        Self::DevDamage {
            entity_id: args.entity_id,
            amount: args.amount,
        }
    }
}

impl __sdk::InModule for DevDamageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `dev_damage`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait dev_damage {
    /// Request that the remote module invoke the reducer `dev_damage` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`dev_damage:dev_damage_then`] to run a callback after the reducer completes.
    fn dev_damage(&self, entity_id: u64, amount: f32) -> __sdk::Result<()> {
        self.dev_damage_then(entity_id, amount, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `dev_damage` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn dev_damage_then(
        &self,
        entity_id: u64,
        amount: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl dev_damage for super::RemoteReducers {
    fn dev_damage_then(
        &self,
        entity_id: u64,
        amount: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DevDamageArgs { entity_id, amount }, callback)
    }
}
