// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DevTeleportArgs {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

impl From<DevTeleportArgs> for super::Reducer {
    fn from(args: DevTeleportArgs) -> Self {
        Self::DevTeleport {
            x: args.x,
            y: args.y,
            z: args.z,
        }
    }
}

impl __sdk::InModule for DevTeleportArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `dev_teleport`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait dev_teleport {
    /// Request that the remote module invoke the reducer `dev_teleport` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`dev_teleport:dev_teleport_then`] to run a callback after the reducer completes.
    fn dev_teleport(&self, x: f32, y: f32, z: f32) -> __sdk::Result<()> {
        self.dev_teleport_then(x, y, z, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `dev_teleport` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn dev_teleport_then(
        &self,
        x: f32,
        y: f32,
        z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl dev_teleport for super::RemoteReducers {
    fn dev_teleport_then(
        &self,
        x: f32,
        y: f32,
        z: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DevTeleportArgs { x, y, z }, callback)
    }
}
