// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_coarse_type::EntityCoarse;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `entity_coarse`.
///
/// Obtain a handle from the [`EntityCoarseTableAccess::entity_coarse`] method on [`super::RemoteTables`],
/// like `ctx.db.entity_coarse()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_coarse().on_insert(...)`.
pub struct EntityCoarseTableHandle<'ctx> {
    imp: __sdk::TableHandle<EntityCoarse>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `entity_coarse`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EntityCoarseTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EntityCoarseTableHandle`], which mediates access to the table `entity_coarse`.
    fn entity_coarse(&self) -> EntityCoarseTableHandle<'_>;
}

impl EntityCoarseTableAccess for super::RemoteTables {
    fn entity_coarse(&self) -> EntityCoarseTableHandle<'_> {
        EntityCoarseTableHandle {
            imp: self.imp.get_table::<EntityCoarse>("entity_coarse"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EntityCoarseInsertCallbackId(__sdk::CallbackId);
pub struct EntityCoarseDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EntityCoarseTableHandle<'ctx> {
    type Row = EntityCoarse;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EntityCoarse> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EntityCoarseInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityCoarseInsertCallbackId {
        EntityCoarseInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EntityCoarseInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EntityCoarseDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EntityCoarseDeleteCallbackId {
        EntityCoarseDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EntityCoarseDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct EntityCoarseUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EntityCoarseTableHandle<'ctx> {
    type UpdateCallbackId = EntityCoarseUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EntityCoarseUpdateCallbackId {
        EntityCoarseUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EntityCoarseUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `entity_id` unique index on the table `entity_coarse`,
/// which allows point queries on the field of the same name
/// via the [`EntityCoarseEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.entity_coarse().entity_id().find(...)`.
pub struct EntityCoarseEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EntityCoarse, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EntityCoarseTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `entity_coarse`.
    pub fn entity_id(&self) -> EntityCoarseEntityIdUnique<'ctx> {
        EntityCoarseEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EntityCoarseEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EntityCoarse> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EntityCoarse>("entity_coarse");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<EntityCoarse>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EntityCoarse>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `EntityCoarse`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait entity_coarseQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `EntityCoarse`.
    fn entity_coarse(&self) -> __sdk::__query_builder::Table<EntityCoarse>;
}

impl entity_coarseQueryTableAccess for __sdk::QueryTableAccessor {
    fn entity_coarse(&self) -> __sdk::__query_builder::Table<EntityCoarse> {
        __sdk::__query_builder::Table::new("entity_coarse")
    }
}
