// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EntityAllocator {
    pub id: u32,
    pub next_entity_id: u64,
    pub next_character_id: u64,
}

impl __sdk::InModule for EntityAllocator {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EntityAllocator`.
///
/// Provides typed access to columns for query building.
pub struct EntityAllocatorCols {
    pub id: __sdk::__query_builder::Col<EntityAllocator, u32>,
    pub next_entity_id: __sdk::__query_builder::Col<EntityAllocator, u64>,
    pub next_character_id: __sdk::__query_builder::Col<EntityAllocator, u64>,
}

impl __sdk::__query_builder::HasCols for EntityAllocator {
    type Cols = EntityAllocatorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityAllocatorCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            next_entity_id: __sdk::__query_builder::Col::new(table_name, "next_entity_id"),
            next_character_id: __sdk::__query_builder::Col::new(table_name, "next_character_id"),
        }
    }
}

/// Indexed column accessor struct for the table `EntityAllocator`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityAllocatorIxCols {
    pub id: __sdk::__query_builder::IxCol<EntityAllocator, u32>,
}

impl __sdk::__query_builder::HasIxCols for EntityAllocator {
    type IxCols = EntityAllocatorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityAllocatorIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EntityAllocator {}
