// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EntityCoarse {
    pub entity_id: u64,
    pub generation: u32,
    pub kind: u32,
    pub cell_id: u64,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub updated_micros: i64,
}

impl __sdk::InModule for EntityCoarse {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EntityCoarse`.
///
/// Provides typed access to columns for query building.
pub struct EntityCoarseCols {
    pub entity_id: __sdk::__query_builder::Col<EntityCoarse, u64>,
    pub generation: __sdk::__query_builder::Col<EntityCoarse, u32>,
    pub kind: __sdk::__query_builder::Col<EntityCoarse, u32>,
    pub cell_id: __sdk::__query_builder::Col<EntityCoarse, u64>,
    pub x: __sdk::__query_builder::Col<EntityCoarse, f32>,
    pub y: __sdk::__query_builder::Col<EntityCoarse, f32>,
    pub z: __sdk::__query_builder::Col<EntityCoarse, f32>,
    pub updated_micros: __sdk::__query_builder::Col<EntityCoarse, i64>,
}

impl __sdk::__query_builder::HasCols for EntityCoarse {
    type Cols = EntityCoarseCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EntityCoarseCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            generation: __sdk::__query_builder::Col::new(table_name, "generation"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            cell_id: __sdk::__query_builder::Col::new(table_name, "cell_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            updated_micros: __sdk::__query_builder::Col::new(table_name, "updated_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `EntityCoarse`.
///
/// Provides typed access to indexed columns for query building.
pub struct EntityCoarseIxCols {
    pub cell_id: __sdk::__query_builder::IxCol<EntityCoarse, u64>,
    pub entity_id: __sdk::__query_builder::IxCol<EntityCoarse, u64>,
}

impl __sdk::__query_builder::HasIxCols for EntityCoarse {
    type IxCols = EntityCoarseIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EntityCoarseIxCols {
            cell_id: __sdk::__query_builder::IxCol::new(table_name, "cell_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EntityCoarse {}
