// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct HeldIntent {
    pub entity_id: u64,
    pub move_x: f32,
    pub move_y: f32,
    pub yaw: f32,
    pub sprint: bool,
    pub grace_ticks: u32,
}

impl __sdk::InModule for HeldIntent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `HeldIntent`.
///
/// Provides typed access to columns for query building.
pub struct HeldIntentCols {
    pub entity_id: __sdk::__query_builder::Col<HeldIntent, u64>,
    pub move_x: __sdk::__query_builder::Col<HeldIntent, f32>,
    pub move_y: __sdk::__query_builder::Col<HeldIntent, f32>,
    pub yaw: __sdk::__query_builder::Col<HeldIntent, f32>,
    pub sprint: __sdk::__query_builder::Col<HeldIntent, bool>,
    pub grace_ticks: __sdk::__query_builder::Col<HeldIntent, u32>,
}

impl __sdk::__query_builder::HasCols for HeldIntent {
    type Cols = HeldIntentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        HeldIntentCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            move_x: __sdk::__query_builder::Col::new(table_name, "move_x"),
            move_y: __sdk::__query_builder::Col::new(table_name, "move_y"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            sprint: __sdk::__query_builder::Col::new(table_name, "sprint"),
            grace_ticks: __sdk::__query_builder::Col::new(table_name, "grace_ticks"),
        }
    }
}

/// Indexed column accessor struct for the table `HeldIntent`.
///
/// Provides typed access to indexed columns for query building.
pub struct HeldIntentIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<HeldIntent, u64>,
}

impl __sdk::__query_builder::HasIxCols for HeldIntent {
    type IxCols = HeldIntentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        HeldIntentIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for HeldIntent {}
