// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MoveTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for MoveTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MoveTimer`.
///
/// Provides typed access to columns for query building.
pub struct MoveTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<MoveTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<MoveTimer, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for MoveTimer {
    type Cols = MoveTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MoveTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `MoveTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct MoveTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<MoveTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for MoveTimer {
    type IxCols = MoveTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MoveTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MoveTimer {}
