// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Npc {
    pub entity_id: u64,
    pub generation: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
    pub zone_id: u32,
    pub kind: u32,
    pub last_update_micros: i64,
}

impl __sdk::InModule for Npc {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Npc`.
///
/// Provides typed access to columns for query building.
pub struct NpcCols {
    pub entity_id: __sdk::__query_builder::Col<Npc, u64>,
    pub generation: __sdk::__query_builder::Col<Npc, u32>,
    pub x: __sdk::__query_builder::Col<Npc, f32>,
    pub y: __sdk::__query_builder::Col<Npc, f32>,
    pub z: __sdk::__query_builder::Col<Npc, f32>,
    pub yaw: __sdk::__query_builder::Col<Npc, f32>,
    pub zone_id: __sdk::__query_builder::Col<Npc, u32>,
    pub kind: __sdk::__query_builder::Col<Npc, u32>,
    pub last_update_micros: __sdk::__query_builder::Col<Npc, i64>,
}

impl __sdk::__query_builder::HasCols for Npc {
    type Cols = NpcCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NpcCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            generation: __sdk::__query_builder::Col::new(table_name, "generation"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            zone_id: __sdk::__query_builder::Col::new(table_name, "zone_id"),
            kind: __sdk::__query_builder::Col::new(table_name, "kind"),
            last_update_micros: __sdk::__query_builder::Col::new(table_name, "last_update_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `Npc`.
///
/// Provides typed access to indexed columns for query building.
pub struct NpcIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<Npc, u64>,
    pub zone_id: __sdk::__query_builder::IxCol<Npc, u32>,
}

impl __sdk::__query_builder::HasIxCols for Npc {
    type IxCols = NpcIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NpcIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            zone_id: __sdk::__query_builder::IxCol::new(table_name, "zone_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Npc {}
