// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PendingInput {
    pub id: u64,
    pub entity_id: u64,
    pub seq: u32,
    pub move_x: f32,
    pub move_y: f32,
    pub yaw: f32,
    pub sprint: bool,
    pub jump: bool,
}

impl __sdk::InModule for PendingInput {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PendingInput`.
///
/// Provides typed access to columns for query building.
pub struct PendingInputCols {
    pub id: __sdk::__query_builder::Col<PendingInput, u64>,
    pub entity_id: __sdk::__query_builder::Col<PendingInput, u64>,
    pub seq: __sdk::__query_builder::Col<PendingInput, u32>,
    pub move_x: __sdk::__query_builder::Col<PendingInput, f32>,
    pub move_y: __sdk::__query_builder::Col<PendingInput, f32>,
    pub yaw: __sdk::__query_builder::Col<PendingInput, f32>,
    pub sprint: __sdk::__query_builder::Col<PendingInput, bool>,
    pub jump: __sdk::__query_builder::Col<PendingInput, bool>,
}

impl __sdk::__query_builder::HasCols for PendingInput {
    type Cols = PendingInputCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PendingInputCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            seq: __sdk::__query_builder::Col::new(table_name, "seq"),
            move_x: __sdk::__query_builder::Col::new(table_name, "move_x"),
            move_y: __sdk::__query_builder::Col::new(table_name, "move_y"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            sprint: __sdk::__query_builder::Col::new(table_name, "sprint"),
            jump: __sdk::__query_builder::Col::new(table_name, "jump"),
        }
    }
}

/// Indexed column accessor struct for the table `PendingInput`.
///
/// Provides typed access to indexed columns for query building.
pub struct PendingInputIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<PendingInput, u64>,
    pub id: __sdk::__query_builder::IxCol<PendingInput, u64>,
}

impl __sdk::__query_builder::HasIxCols for PendingInput {
    type IxCols = PendingInputIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PendingInputIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PendingInput {}
