// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PingArgs {
    pub nonce: u64,
}

impl From<PingArgs> for super::Reducer {
    fn from(args: PingArgs) -> Self {
        Self::Ping { nonce: args.nonce }
    }
}

impl __sdk::InModule for PingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ping`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ping {
    /// Request that the remote module invoke the reducer `ping` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ping:ping_then`] to run a callback after the reducer completes.
    fn ping(&self, nonce: u64) -> __sdk::Result<()> {
        self.ping_then(nonce, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ping` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ping_then(
        &self,
        nonce: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ping for super::RemoteReducers {
    fn ping_then(
        &self,
        nonce: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PingArgs { nonce }, callback)
    }
}
