// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub entity_id: u64,
    pub generation: u32,
    pub owner_identity: __sdk::Identity,
    pub character_id: u64,
    pub session: Option<__sdk::ConnectionId>,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub vx: f32,
    pub vy: f32,
    pub vz: f32,
    pub yaw: f32,
    pub zone_id: u32,
    pub epoch: u32,
    pub last_input_seq: u32,
    pub last_update_micros: i64,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub entity_id: __sdk::__query_builder::Col<Player, u64>,
    pub generation: __sdk::__query_builder::Col<Player, u32>,
    pub owner_identity: __sdk::__query_builder::Col<Player, __sdk::Identity>,
    pub character_id: __sdk::__query_builder::Col<Player, u64>,
    pub session: __sdk::__query_builder::Col<Player, Option<__sdk::ConnectionId>>,
    pub x: __sdk::__query_builder::Col<Player, f32>,
    pub y: __sdk::__query_builder::Col<Player, f32>,
    pub z: __sdk::__query_builder::Col<Player, f32>,
    pub vx: __sdk::__query_builder::Col<Player, f32>,
    pub vy: __sdk::__query_builder::Col<Player, f32>,
    pub vz: __sdk::__query_builder::Col<Player, f32>,
    pub yaw: __sdk::__query_builder::Col<Player, f32>,
    pub zone_id: __sdk::__query_builder::Col<Player, u32>,
    pub epoch: __sdk::__query_builder::Col<Player, u32>,
    pub last_input_seq: __sdk::__query_builder::Col<Player, u32>,
    pub last_update_micros: __sdk::__query_builder::Col<Player, i64>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            generation: __sdk::__query_builder::Col::new(table_name, "generation"),
            owner_identity: __sdk::__query_builder::Col::new(table_name, "owner_identity"),
            character_id: __sdk::__query_builder::Col::new(table_name, "character_id"),
            session: __sdk::__query_builder::Col::new(table_name, "session"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            vx: __sdk::__query_builder::Col::new(table_name, "vx"),
            vy: __sdk::__query_builder::Col::new(table_name, "vy"),
            vz: __sdk::__query_builder::Col::new(table_name, "vz"),
            yaw: __sdk::__query_builder::Col::new(table_name, "yaw"),
            zone_id: __sdk::__query_builder::Col::new(table_name, "zone_id"),
            epoch: __sdk::__query_builder::Col::new(table_name, "epoch"),
            last_input_seq: __sdk::__query_builder::Col::new(table_name, "last_input_seq"),
            last_update_micros: __sdk::__query_builder::Col::new(table_name, "last_update_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub character_id: __sdk::__query_builder::IxCol<Player, u64>,
    pub entity_id: __sdk::__query_builder::IxCol<Player, u64>,
    pub owner_identity: __sdk::__query_builder::IxCol<Player, __sdk::Identity>,
    pub zone_id: __sdk::__query_builder::IxCol<Player, u32>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            character_id: __sdk::__query_builder::IxCol::new(table_name, "character_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            owner_identity: __sdk::__query_builder::IxCol::new(table_name, "owner_identity"),
            zone_id: __sdk::__query_builder::IxCol::new(table_name, "zone_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}
