// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Projectile {
    pub entity_id: u64,
    pub caster_entity_id: u64,
    pub ability_id: u16,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub vx: f32,
    pub vy: f32,
    pub vz: f32,
    pub zone_id: u32,
    pub spawned_at_micros: i64,
    pub last_update_micros: i64,
}

impl __sdk::InModule for Projectile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Projectile`.
///
/// Provides typed access to columns for query building.
pub struct ProjectileCols {
    pub entity_id: __sdk::__query_builder::Col<Projectile, u64>,
    pub caster_entity_id: __sdk::__query_builder::Col<Projectile, u64>,
    pub ability_id: __sdk::__query_builder::Col<Projectile, u16>,
    pub x: __sdk::__query_builder::Col<Projectile, f32>,
    pub y: __sdk::__query_builder::Col<Projectile, f32>,
    pub z: __sdk::__query_builder::Col<Projectile, f32>,
    pub vx: __sdk::__query_builder::Col<Projectile, f32>,
    pub vy: __sdk::__query_builder::Col<Projectile, f32>,
    pub vz: __sdk::__query_builder::Col<Projectile, f32>,
    pub zone_id: __sdk::__query_builder::Col<Projectile, u32>,
    pub spawned_at_micros: __sdk::__query_builder::Col<Projectile, i64>,
    pub last_update_micros: __sdk::__query_builder::Col<Projectile, i64>,
}

impl __sdk::__query_builder::HasCols for Projectile {
    type Cols = ProjectileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ProjectileCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            caster_entity_id: __sdk::__query_builder::Col::new(table_name, "caster_entity_id"),
            ability_id: __sdk::__query_builder::Col::new(table_name, "ability_id"),
            x: __sdk::__query_builder::Col::new(table_name, "x"),
            y: __sdk::__query_builder::Col::new(table_name, "y"),
            z: __sdk::__query_builder::Col::new(table_name, "z"),
            vx: __sdk::__query_builder::Col::new(table_name, "vx"),
            vy: __sdk::__query_builder::Col::new(table_name, "vy"),
            vz: __sdk::__query_builder::Col::new(table_name, "vz"),
            zone_id: __sdk::__query_builder::Col::new(table_name, "zone_id"),
            spawned_at_micros: __sdk::__query_builder::Col::new(table_name, "spawned_at_micros"),
            last_update_micros: __sdk::__query_builder::Col::new(table_name, "last_update_micros"),
        }
    }
}

/// Indexed column accessor struct for the table `Projectile`.
///
/// Provides typed access to indexed columns for query building.
pub struct ProjectileIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<Projectile, u64>,
    pub zone_id: __sdk::__query_builder::IxCol<Projectile, u32>,
}

impl __sdk::__query_builder::HasIxCols for Projectile {
    type IxCols = ProjectileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ProjectileIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            zone_id: __sdk::__query_builder::IxCol::new(table_name, "zone_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Projectile {}
