// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RunParityTraceArgs {
    pub trace_id: String,
}

impl From<RunParityTraceArgs> for super::Reducer {
    fn from(args: RunParityTraceArgs) -> Self {
        Self::RunParityTrace {
            trace_id: args.trace_id,
        }
    }
}

impl __sdk::InModule for RunParityTraceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `run_parity_trace`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait run_parity_trace {
    /// Request that the remote module invoke the reducer `run_parity_trace` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`run_parity_trace:run_parity_trace_then`] to run a callback after the reducer completes.
    fn run_parity_trace(&self, trace_id: String) -> __sdk::Result<()> {
        self.run_parity_trace_then(trace_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `run_parity_trace` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn run_parity_trace_then(
        &self,
        trace_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl run_parity_trace for super::RemoteReducers {
    fn run_parity_trace_then(
        &self,
        trace_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RunParityTraceArgs { trace_id }, callback)
    }
}
