// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SubmitInputArgs {
    pub epoch: u32,
    pub seq: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub yaw: f32,
}

impl From<SubmitInputArgs> for super::Reducer {
    fn from(args: SubmitInputArgs) -> Self {
        Self::SubmitInput {
            epoch: args.epoch,
            seq: args.seq,
            x: args.x,
            y: args.y,
            z: args.z,
            yaw: args.yaw,
        }
    }
}

impl __sdk::InModule for SubmitInputArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `submit_input`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait submit_input {
    /// Request that the remote module invoke the reducer `submit_input` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`submit_input:submit_input_then`] to run a callback after the reducer completes.
    fn submit_input(
        &self,
        epoch: u32,
        seq: u32,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,
    ) -> __sdk::Result<()> {
        self.submit_input_then(epoch, seq, x, y, z, yaw, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `submit_input` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn submit_input_then(
        &self,
        epoch: u32,
        seq: u32,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl submit_input for super::RemoteReducers {
    fn submit_input_then(
        &self,
        epoch: u32,
        seq: u32,
        x: f32,
        y: f32,
        z: f32,
        yaw: f32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SubmitInputArgs {
                epoch,
                seq,
                x,
                y,
                z,
                yaw,
            },
            callback,
        )
    }
}
