// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Tombstone {
    pub entity_id: u64,
    pub generation: u32,
    pub despawned_at_micros: i64,
}

impl __sdk::InModule for Tombstone {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Tombstone`.
///
/// Provides typed access to columns for query building.
pub struct TombstoneCols {
    pub entity_id: __sdk::__query_builder::Col<Tombstone, u64>,
    pub generation: __sdk::__query_builder::Col<Tombstone, u32>,
    pub despawned_at_micros: __sdk::__query_builder::Col<Tombstone, i64>,
}

impl __sdk::__query_builder::HasCols for Tombstone {
    type Cols = TombstoneCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TombstoneCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            generation: __sdk::__query_builder::Col::new(table_name, "generation"),
            despawned_at_micros: __sdk::__query_builder::Col::new(
                table_name,
                "despawned_at_micros",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `Tombstone`.
///
/// Provides typed access to indexed columns for query building.
pub struct TombstoneIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<Tombstone, u64>,
}

impl __sdk::__query_builder::HasIxCols for Tombstone {
    type IxCols = TombstoneIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TombstoneIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Tombstone {}
